sim:
 environment: local # Can be "hopper" or "local". Changes some of the logging to make sense for big sims.

geo: 
  # Envelope for grid/continuous space for the simulation. Must be integers
  # Also the path to the geotiff to use.
  x_min: 1613845
  x_max: 1637295
  y_min: 1950165
  y_max: 1973355
 
  tiff_path: ./input/images/2019_CONUS_Canopy.tiff #in relation to project root dir
  buffer_size: 10 # max number of pixels that an agent can move in a single tick
 
time: 
  start_time: "2000-01-01T00:00:00" #ISO 8601 Timestamp
  hours_per_tick: 1
  end_tick: 1000
 
logging:
  # loglevel: DEBUG # can be DEBUG, INFO, WARNING, ERROR
  loglevel: INFO
  # loglevel: WARNING
  # loglevel: ERROR
  agent_log_file: './output/benchmark_01.csv' 
 
deer:
  pop_size: 100000 # Number of deer agents to simulate
  disease_starting_ratio: 0 # What ratio of deer start sim being sick. 
 
deer_control_vars:  # From https://www.researchgate.net/publication/363077733_The_effect_of_landscape_transmission_mode_and_social_behavior_on_disease_transmission_Simulating_the_transmission_of_chronic_wasting_disease_in_white-tailed_deer_Odocoileus_virginianus_populations_usi
  male_disperse_prob: 0.7 # (Hawkins et al., 1971; Nixon et al., 2007, 1994; Rosenberry et al., 1999) 
  female_disperse_prob: 0.2 # (Hawkins et al., 1971; Nixon et al., 2007, 1994; Rosenberry et al., 1999) 
  explore_chance:
    gestation: 0.32
    fawning: 0.08
    prerut: 0.2
    rut: 0.96
    duration: 
      min: 12 
      max: 24 #Hours
  gestation:
    min: 187 #Daysx
    max: 222 #Days
    fawn_prob:
      one: 0.25
      two: 0.5
      three: 0.25
  grouping:
    adhesion:
      female: 
        normal: 0.95
        fawning: 0
      male:
        normal: 0.4
        rut: 0
    size_max:
      male: 10
      female: 4
  annual_mortality:
    female: 0.2
    male: 0.4
    fawn: 0.2
  # annual_schedule: #ISO8601 --MM-DD .strftime('%m-%d')
  #   gestation_start: 01-01
  #   fawning_start: 05-15
  #   prerut_start: 09-01
  #   rut_start: 11-01
  age:
    fawn_to_adult: 360 # days. Fawn grows up
    adult_max: 100000 # days. Max age of agents
  homerange:
    max: 100
    min: 50
    suitability_threshold: 60 

  #TODO: put file in here controlling the deer movement 
