sim:
 environment: local # Can be "hopper" or "local". Changes some of the logging to make sense for big sims.

geo: 
  # Envelope for grid/continuous space for the simulation. Must be integers
  # Dummy bounding box for Fairfax in EPSG 5070  

  x_min: 1603796
  x_max: 1607728
  y_min: 1964280
  y_max: 1967004


  # x_min: 1603849
  # x_max: 1637294
  # y_min: 1950179
  # y_max: 1973346
  buffer_size: 20 # max number of pixels that an agent can move in a single tick

time: 
  start_time: "2000-01-01T00:00:00" #ISO 8601 Timestamp
  hours_per_tick: 1
  end_tick: 300
 
logging:
  loglevel: INFO # can be DEBUG, INFO, WARNING, ERROR
  agent_log_file: 'output/agent_log.csv'
 
deer:
  pop_size: 300 # Number of deer agents to simulate
  disease_starting_ratio: 0 # What ratio of deer start sim being sick.
  input_agents: 'input/deer_agents.parq' # Starting params for each deer agent.
 
deer_control_vars:  # From https://www.researchgate.net/publication/363077733_The_effect_of_landscape_transmission_mode_and_social_behavior_on_disease_transmission_Simulating_the_transmission_of_chronic_wasting_disease_in_white-tailed_deer_Odocoileus_virginianus_populations_usi
  male_disperse_prob: 0.7 # (Hawkins et al., 1971; Nixon et al., 2007, 1994; Rosenberry et al., 1999) 
  female_disperse_prob: 0.2 # (Hawkins et al., 1971; Nixon et al., 2007, 1994; Rosenberry et al., 1999) 
  explore_chance:
    gestation: 0.32
    fawning: 0.08
    prerut: 0.2
    rut: 0.96
    duration: 
      min: 12 
      max: 24 #Hours
  gestation:
    min: 187 #Daysx
    max: 222 #Days
    fawn_prob:
      one: 0.25
      two: 0.5
      three: 0.25
  grouping:
    adhesion:
      female: 
        normal: 0.95
        fawning: 0
      male:
        normal: 0.4
        rut: 0
    size_max:
      male: 10
      female: 4
  annual_mortality:
    female: 0.2
    male: 0.4
    fawn: 0.2
  annual_schedule: #ISO8601 --MM-DD .strftime('%m-%d')
    gestation_start: 01-01
    fawning_start: 05-15
    prerut_start: 09-01
    rut_start: 11-01
  age:
    fawn_to_adult: 12 #months
    adult_max: 100 #months. Max age of agents

  #TODO: put file in here controlling the deer movement 
